### ISSUE TITLE
VScodium doesn't start on Linux Mint 19.3

### ISSUE THREAD

**Issue by Mek101** [flathub/com.vscodium.codium#20]
Starting the application from the desktop file or command line fails on Linux Mint 19.3

With the desktop file or the `flatpak run com.vscodium.codium` command there's no output, while instead, passing the full command and options listed on the desktop file results in 
```
mek101@mint19-desktop:~$ flatpak run --branch=stable --arch=x86_64 --command=/app/bin/codium --file-forwarding com.vscodium.codium --unity-launch -F
Warning: 'F' is not in the list of known options, but still passed to Electron/Chromium.
```

Using [this](https://github.com/flathub/com.vscodium.codium/issues/3#issuecomment-636732665) as a reference, i attempted to get some diagnosis, which resulted in the following:
```
mek101@mint19-desktop:~$ flatpak run com.vscodium.codium --log debug --verbose
[20:0818/130351.517099:ERROR:address_tracker_linux.cc(171)] Could not bind NETLINK socket: Indirizzo già in uso (98)
(node:20) UnhandledPromiseRejectionWarning: Error: The "path" argument must be of type string. Received type undefined
    at h (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:69:918)
    at Object.join (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:77:226)
    at /app/share/codium/resources/app/out/vs/code/electron-main/main.js:340:451
    at v (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:340:760)
    at get mainIPCHandle (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:337:632)
    at g.r.<computed> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:7:790)
    at Object.patchEnvironment (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:631:281)
    at Object.createServices (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:878)
    at Object.startup (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:155)
    at Object.main (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:83)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:634:136)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:318)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:21:555)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:161)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:401)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:31:694)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:25:782)
    at o (/app/share/codium/resources/app/out/vs/loader.js:30:163)
    at Object.l (/app/share/codium/resources/app/out/vs/loader.js:38:67)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:318)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:21:555)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:161)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:401)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:31:694)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:25:782)
    at r (/app/share/codium/resources/app/out/vs/loader.js:32:838)
    at c (/app/share/codium/resources/app/out/vs/loader.js:17:685)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.nls.js:4:1)
    at t._createAndEvalScript (/app/share/codium/resources/app/out/vs/loader.js:17:729)
    at /app/share/codium/resources/app/out/vs/loader.js:17:366
    at u (/app/share/codium/resources/app/out/vs/loader.js:19:219)
    at /app/share/codium/resources/app/out/vs/loader.js:19:416
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:20) UnhandledPromiseRejectionWarning: Error: The "path" argument must be of type string. Received type undefined
    at h (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:69:918)
    at Object.join (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:77:226)
    at /app/share/codium/resources/app/out/vs/code/electron-main/main.js:340:451
    at v (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:340:760)
    at get mainIPCHandle (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:337:632)
    at g.r.<computed> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:7:790)
    at Object.patchEnvironment (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:631:281)
    at Object.createServices (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:878)
    at Object.startup (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:155)
    at Object.main (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:629:83)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:634:136)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:318)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:21:555)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:161)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:401)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:31:694)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:25:782)
    at o (/app/share/codium/resources/app/out/vs/loader.js:30:163)
    at Object.l (/app/share/codium/resources/app/out/vs/loader.js:38:67)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:71)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:318)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:21:555)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:161)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:401)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:31:694)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:25:782)
    at r (/app/share/codium/resources/app/out/vs/loader.js:32:838)
    at c (/app/share/codium/resources/app/out/vs/loader.js:17:685)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.nls.js:4:1)
    at t._createAndEvalScript (/app/share/codium/resources/app/out/vs/loader.js:17:729)
    at /app/share/codium/resources/app/out/vs/loader.js:17:366
    at u (/app/share/codium/resources/app/out/vs/loader.js:19:219)
    at /app/share/codium/resources/app/out/vs/loader.js:19:416
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[56:0818/130351.977461:ERROR:address_tracker_linux.cc(171)] Could not bind NETLINK socket: Indirizzo già in uso (98)
```
The application didn't display anything and stalled until killed with ctrl+c

**Comment by Mek101** [comment]
Somehow now works on Linux 20. Closing the issue

**Comment by noonsleeper** [comment]
> Somehow now works on Linux 20. Closing the issue

Nice to know about it, =)
