### ISSUE TITLE
VSCodium does not start on Linux Mint 19.3

### ISSUE THREAD

**Issue by typetester** [flathub/com.vscodium.codium#29]
VSCodium does not start from the command line or any other way, debug reads like this:
baba@Duke-XH310:~$ flatpak run com.vscodium.codium --log debug --verbose
[49:1229/095035.329567:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:20) UnhandledPromiseRejectionWarning: Error: The "path" argument must be of type string. Received type undefined
    at d (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:71:660)
    at Object.join (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:78:950)
    at Object.t.createStaticIPCHandle (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:216:826)
    at l.get mainIPCHandle (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:353:106)
    at l.r.<computed> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:7:806)
    at Object.patchEnvironment (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:653:798)
    at Object.createServices (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:652:546)
    at Object.startup (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:651:838)
    at Object.main (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:651:766)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.js:657:392)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:548)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:795)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:22:10)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:623)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:863)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:32:174)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:26:184)
    at o (/app/share/codium/resources/app/out/vs/loader.js:30:565)
    at Object.l (/app/share/codium/resources/app/out/vs/loader.js:38:482)
    at Function.t._safeInvokeFunction (/app/share/codium/resources/app/out/vs/loader.js:21:548)
    at Function.t._invokeFactory (/app/share/codium/resources/app/out/vs/loader.js:21:795)
    at t.complete (/app/share/codium/resources/app/out/vs/loader.js:22:10)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:623)
    at s._onModuleComplete (/app/share/codium/resources/app/out/vs/loader.js:32:863)
    at s._resolve (/app/share/codium/resources/app/out/vs/loader.js:32:174)
    at s.defineModule (/app/share/codium/resources/app/out/vs/loader.js:26:184)
    at n (/app/share/codium/resources/app/out/vs/loader.js:33:308)
    at c (/app/share/codium/resources/app/out/vs/loader.js:17:806)
    at Object.<anonymous> (/app/share/codium/resources/app/out/vs/code/electron-main/main.nls.js:4:1)
    at t._createAndEvalScript (/app/share/codium/resources/app/out/vs/loader.js:17:850)
    at /app/share/codium/resources/app/out/vs/loader.js:17:487
    at u (/app/share/codium/resources/app/out/vs/loader.js:19:421)
    at /app/share/codium/resources/app/out/vs/loader.js:19:618
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by noonsleeper** [comment]
hey could you try 
```bash
sudo apt update
sudo apt upgrade -y flatpak
sudo flatpak uninstall -y com.vscodium.codium
sudo flatpak repair
sudo flatpak install -y com.vscodium.codium
```

**Comment by typetester** [comment]
That didn't help I'm afraid. I did upgrade to Mint 20 and that solved the issue.

**Comment by noonsleeper** [comment]
> That didn't help I'm afraid. I did upgrade to Mint 20 and that solved the issue.

Great to read that, then I'll close this issue. If you still having problems with, please don't hesitate to open a new ticket. =)
